### ISSUE TITLE
the stars are not showing

### ISSUE THREAD

**Issue by KarimFikani** [codemybrainsout/smart-app-rate#2]
I'm running on Nexus 5X API 24 emulator and the stars are not showing in the popup window.
See attached screenshot. Both "Never" and "Maybe Later" buttons work fine but when I click on the stars are I get the following crash:

Fatal Exception: android.content.ActivityNotFoundException: No Activity found to handle Intent { act=android.intent.action.VIEW dat=market://details?id=com.alef.learn.arabicforkids }
       at android.app.Instrumentation.checkStartActivityResult(Instrumentation.java:1809)
       at android.app.Instrumentation.execStartActivity(Instrumentation.java:1523)
       at android.app.Activity.startActivityForResult(Activity.java:4224)
       at android.support.v4.app.BaseFragmentActivityJB.startActivityForResult(BaseFragmentActivityJB.java:48)
       at android.support.v4.app.FragmentActivity.startActivityForResult(FragmentActivity.java:75)
       at android.app.Activity.startActivityForResult(Activity.java:4183)
       at android.support.v4.app.FragmentActivity.startActivityForResult(FragmentActivity.java:856)
       at android.app.Activity.startActivity(Activity.java:4507)
       at android.app.Activity.startActivity(Activity.java:4475)
       at com.codemybrainsout.ratingdialog.RatingDialog.openPlaystore(RatingDialog.java:230)
       at com.codemybrainsout.ratingdialog.RatingDialog.onRatingChanged(RatingDialog.java:199)
       at android.widget.RatingBar.dispatchRatingChange(RatingBar.java:317)
       at android.widget.RatingBar.onStopTrackingTouch(RatingBar.java:305)

![screenshot_1478504756](https://cloud.githubusercontent.com/assets/2486075/20049952/4ca5ced2-a47b-11e6-81bd-4274bf0295fc.png)

**Comment by codemybrainsout** [comment]
@karimfikani Have you tried changing the RatingBar color using `builder.ratingBarColor(R.color.yellow)`?

And regarding the `ActivityNotFoundException`, It is happening because the emulator doesn't have Google PlayStore installed in it. It should work fine on a smartphone with PlayStore installed. However, I've still added the code to handle the exception.
