### ISSUE TITLE
RatingDialog layout doesn´t initialize right

### ISSUE THREAD

**Issue by hoeztur** [codemybrainsout/smart-app-rate#26]
Hi,

when I start the Rating dialog like this:

        final RatingDialog ratingDialog = new RatingDialog.Builder(this)
                .threshold(4)
                .session(5)
                .title(getString(R.string.ratingTitle))
                .titleTextColor(R.color.colorPrimaryDark)
                .positiveButtonText(getString(R.string.positiveBtnRatin))
                .negativeButtonText(getString(R.string.negativeBtnRating))
                .positiveButtonTextColor(R.color.colorAccent)
                .negativeButtonTextColor(R.color.textGray)
                .formTitle(getString(R.string.submitFeedbackTitle))
                .formHint(getString(R.string.feedbackHint))
                .formSubmitText(getString(R.string.feedbackSubmit))
                .formCancelText(getString(R.string.feedbackCancel))
                .ratingBarColor(R.color.colorAccent)
             ).build();

        ratingDialog.show();

I get this error:

Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'void android.widget.TextView.setText(java.lang.CharSequence)' on a null object reference
                                                                      at com.codemybrainsout.ratingdialog.RatingDialog.init(RatingDialog.java:86)
                                                                      at com.codemybrainsout.ratingdialog.RatingDialog.onCreate(RatingDialog.java:81)
                                                                      at android.app.Dialog.dispatchOnCreate(Dialog.java:402)
                                                                      at android.app.Dialog.show(Dialog.java:301)

The Debugging tells me that the layout is not correct loaded, however any solution? The Strange thing is it worked, with the exact same implementation some days ago.

**Comment by alexjcrowley** [comment]
What line in the initialisation is giving the issue? I assume it is one of the lines to set the text on the different elements.

**Comment by ahulr** [comment]
Closing due to inactivity.
